name: Snyk Scan and SARIF Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and Snyk CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }} 

      # - name: Run Snyk Scan
      #   run: snyk test --all-projects --json > snyk_results.json || true
      #   continue-on-error: true
      
      - name: Run Snyk IaC Scan
        run: snyk iac test  --json > snyk_results.json || true
        continue-on-error: true

      - name: Verify Snyk Results JSON
        run: |
          echo "Checking if snyk_results.json file exists:"
          ls -l snyk_results.json
          cat snyk_results.json  # Display contents of the JSON file for debugging

          

      - name: Upload Snyk Results as Artifact
        if: success() || failure()  # Ensure artifact upload runs regardless of the previous step's success/failure
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: snyk_results.json

      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif
        


  upload_sarif:
    name: Upload SARIF
    needs: snyk_scan
    runs-on: ubuntu-latest

    steps:
      - name: Download Snyk Results
        uses: actions/download-artifact@v2
        with:
          name: snyk-results
         
      - name: Verify Snyk Results JSON
        run: |
          echo "Checking if snyk_results.json file was downloaded:"
          ls -l snyk_results.json
          cat snyk_results.json  # Display contents of the JSON file for debugging


      - name: Install snyk-to-sarif
        run: npm install -g snyk-to-sarif

      - name: Convert Snyk JSON Results to SARIF
        run: |
          npx snyk-to-sarif --inputFile snyk_results.json --outputFile snyk_results.sarif
          if [ $? -ne 0 ]; then
            echo "Failed to convert snyk_results.json to SARIF."
            exit 1
          fi

      - name: Verify SARIF File
        run: |
          echo "Checking if snyk_results.sarif file was created:"
          ls -l snyk_results.sarif

      - name: Upload SARIF File
        if: success() || failure()  # Ensure SARIF upload runs regardless of the previous step's success/failure
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_results.sarif